# COMBINES ALL APPLICATION CONTAINERS
version: '3.9'
services:
  backend:
    image: everybody-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: ./
      dockerfile: src/Dockerfile
    ports:
      - "4567"
    expose:
      - "8080"
  web:
    image: everybody-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: 'npm start'
    depends_on:
      - backend
