version: '3.9'
services:
  backend:
    image: everybody-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    build:
      context: ./
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"
      - "4567:4567"
    command: >
      sh -c "mvn clean package -Djacoco.skip=true &&
            ./run"
  web:
    image: everybody-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: 'npm start'
    depends_on:
      - backend
