# COMBINES ALL APPLICATION CONTAINERS
version: '3.9'
services:
  web:
    image: node:alpine
  db:
    image: postgres
    environment:
      # TODO: create more secure access settings for DB
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='cs32-final-server!'
      - POSTGRES_DB=everybody_db
    ports:
      - '5432:5432'
    volumes:
      - db-data:/data/postgresql
  backend:
    image: everybody-app
    build:
      context: ./src
      dockerfile: src/Dockerfile

volumes:
  db-data:
