# COMBINES ALL APPLICATION CONTAINERS
version: '3.9'
services:
  backend:
    image: everybody-app
    build:
      context: ./
      dockerfile: src/Dockerfile
# TODO: may not need DB details here
#  db:
#    image: postgres:latest
#    ports:
#      - 5432:5432
  web:
    image: everybody-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: 'npm start'
    depends_on:
      - backend
#      - db
