# COMBINES ALL APPLICATION CONTAINERS
version: '3.9'
services:
  web:
    image: everybody-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: 'npm start'
  backend:
    image: everybody-app
    build:
      context: ./
      dockerfile: src/Dockerfile
