# COMBINES ALL APPLICATION CONTAINERS (FOR HEROKU DEPLOYMENT)
version: '3.9'
services:
  backend:
    image: everybody-app
    build:
      context: ./
      dockerfile: src/Dockerfile
  web:
    image: everybody-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: 'npm start'
    depends_on:
      - backend